  dev[m
* [32mmain[m
  sa-add-cart-issue[m
  sa-admin-category-book-endpoints[m
  sa-admin-public-lfp[m
  sa-admin-search-filter[m
  sa-book-detail[m
  sa-cart-crud[m
  sa-checkout-order-confirm[m
  sa-cors[m
  sa-file-manage[m
  sa-forgot-reset[m
  sa-image-object-key[m
  sa-image-profile[m
  sa-logout-forgot-profile[m
  sa-migration-issue[m
  sa-missing-dependencies[m
  sa-ngnix[m
  sa-orderhistory-address[m
  sa-public-endpoints[m
  sa-r2objectstorage[m
  sa-reviews-crud[m
  sa-server-503[m
  sa-storager2-buckets3[m
  sa-update-book-model[m
  sa-uploads[m
  sa-wishlist[m
  update-profile[m
