"""Add profile_image column

Revision ID: 068f4aa45392
Revises: 3dfc0208ceeb
Create Date: 2025-12-09 10:39:37.963283

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '068f4aa45392'
down_revision: Union[str, Sequence[str], None] = '3dfc0208ceeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('user', sa.Column('profile_image', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_image')
    
    
    

    
   
   
  
    
    
   
    

    # ### end Alembic commands ###
