"""add ebook fields to book and ebook_payment table

Revision ID: 2e713e304f9e
Revises: 1cdc3e5a41cb
Create Date: 2026-01-09 15:53:40.288577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '2e713e304f9e'
down_revision: Union[str, Sequence[str], None] = '1cdc3e5a41cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ebookpayment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ebook_purchase_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('txn_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ebook_purchase_id'], ['ebookpurchase.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('book', sa.Column('is_ebook', sa.Boolean(), nullable=True))
    op.execute("UPDATE book SET is_ebook = FALSE")
    op.alter_column(
        "book",
        "is_ebook",
        nullable=False
    )
    op.add_column('book', sa.Column('ebook_price', sa.Float(), nullable=True))
   
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    
    op.drop_column('book', 'ebook_price')
    op.drop_column('book', 'is_ebook')

    op.drop_table('ebookpayment')
    # ### end Alembic commands ###
