"""Add created_at back to wishlist

Revision ID: 9dab0afba83e
Revises: 21d761ab0a3a
Create Date: 2025-12-11 15:53:16.055641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dab0afba83e'
down_revision: Union[str, Sequence[str], None] = '21d761ab0a3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orderitem')
    op.add_column('wishlist', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wishlist', 'created_at')
    op.create_table('orderitem',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('book_title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name=op.f('orderitem_book_id_fkey')),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name=op.f('orderitem_order_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('orderitem_pkey'))
    )
    # ### end Alembic commands ###
