"""sync models after cleanup

Revision ID: c095268c86e6
Revises: 9dab0afba83e
Create Date: 2025-12-12 15:59:01.087942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c095268c86e6'
down_revision: Union[str, Sequence[str], None] = '9dab0afba83e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orderitem')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orderitem',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('book_title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name=op.f('orderitem_book_id_fkey')),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name=op.f('orderitem_order_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('orderitem_pkey'))
    )
    # ### end Alembic commands ###
