"""add order_summary table

Revision ID: cd43547e4881
Revises: abb942245946
Create Date: 2026-01-06 01:11:22.654931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd43547e4881'
down_revision: Union[str, Sequence[str], None] = 'abb942245946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('shipping', sa.Float(), nullable=False),
    sa.Column('tax', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('items_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='bookstore'
    )
    op.create_index(op.f('ix_bookstore_order_summary_order_id'), 'order_summary', ['order_id'], unique=False, schema='bookstore')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookstore_order_summary_order_id'), table_name='order_summary', schema='bookstore')
    op.drop_table('order_summary', schema='bookstore')
    # ### end Alembic commands ###