"""payment mode placed by added to order

Revision ID: d15af49322a6
Revises: [previous_revision]
Create Date: [date]

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd15af49322a6'
down_revision: Union[str, Sequence[str], None] = '53831d44a75b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.alter_column('review', 'user_id', nullable=True)  # Inside function


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review', 'user_id', nullable=False)
    # ### end Alembic commands ###