"""payment_mode & placed_by added to order model

Revision ID: d15af49322a6
Revises: 53831d44a75b
Create Date: 2026-01-05 14:57:27.794161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd15af49322a6'
down_revision: Union[str, Sequence[str], None] = '53831d44a75b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('placed_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute("UPDATE \"order\" SET placed_by = 'user' WHERE placed_by IS NULL")
    op.alter_column(
        'order',
        'placed_by',
        nullable=False
    )
    op.add_column('order', sa.Column('payment_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('order', sa.Column('payment_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute("UPDATE \"order\" SET payment_mode = 'online' WHERE payment_mode IS NULL")

    op.alter_column(
    'order',
    'payment_mode',
    nullable=False
)
    # 1. Temporarily allow NULL (if not already)
op.alter_column('review', 'user_id', nullable=True)

# 2. Backfill existing NULLs
op.execute(
    "UPDATE review SET user_id = 1 WHERE user_id IS NULL"
)

# 3. Enforce NOT NULL
op.alter_column('review', 'user_id', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('notification',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('recipient_role', postgresql.ENUM('admin', 'customer', name='recipientrole'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('trigger_source', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('related_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('channel', postgresql.ENUM('email', 'sms', 'system', name='notificationchannel'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('sent', 'failed', name='notificationstatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('notification_pkey'))
    )
    op.create_table('sociallinks',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('facebook', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('youtube', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('twitter', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('whatsapp', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('sociallinks_pkey'))
    )
    op.create_table('payment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('txn_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('method', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('payment_pkey'))
    )
    op.create_index(op.f('ix_payment_user_id'), 'payment', ['user_id'], unique=False)
    op.create_index(op.f('ix_payment_txn_id'), 'payment', ['txn_id'], unique=True)
    op.create_index(op.f('ix_payment_order_id'), 'payment', ['order_id'], unique=False)
    op.create_table('generalsettings',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('site_logo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('site_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('store_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contact_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('generalsettings_pkey'))
    )
    # ### end Alembic commands ###
