"""add fk to notification user

Revision ID: d4e6b2af39bb
Revises: a1bd0da8662d
Create Date: 2026-02-18 15:59:23.484315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd4e6b2af39bb'
down_revision: Union[str, Sequence[str], None] = 'a1bd0da8662d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emaillog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_book_image_book_id'), table_name='book_image')
    op.drop_table('book_image')
    op.drop_table('email_log')
    op.drop_table('cancellationrequest')
    op.drop_index(op.f('ix_order_event_event_type'), table_name='order_event')
    op.drop_index(op.f('ix_order_event_order_id'), table_name='order_event')
    op.drop_table('order_event')
    op.alter_column('book', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_book_is_deleted'), 'book', ['is_deleted'], unique=False)
    op.drop_constraint(op.f('book_category_id_fkey'), 'book', type_='foreignkey')
    op.create_index(op.f('ix_ebookpurchase_gateway_order_id'), 'ebookpurchase', ['gateway_order_id'], unique=False)
    op.drop_column('ebookpurchase', 'renewal_count')
    op.drop_column('ebookpurchase', 'last_renewed_at')
    op.create_foreign_key(None, 'notification', 'user', ['user_id'], ['id'])
    op.drop_column('order', 'payment_method')
    op.alter_column('payment', 'txn_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_payment_user_id'), table_name='payment')
    op.drop_constraint(op.f('uq_payment_order_method'), 'payment', type_='unique')
    op.drop_constraint(op.f('uq_payment_txn_id'), 'payment', type_='unique')
    op.drop_index(op.f('ix_payment_txn_id'), table_name='payment')
    op.create_index(op.f('ix_payment_txn_id'), 'payment', ['txn_id'], unique=True)
    op.create_foreign_key(None, 'payment', 'user', ['user_id'], ['id'])
    op.drop_column('payment', 'currency')
    op.drop_column('payment', 'gateway_signature')
    op.drop_column('payment', 'gateway_order_id')
    op.drop_column('payment', 'gateway_response')
    op.drop_column('payment', 'failure_reason')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('failure_reason', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('payment', sa.Column('gateway_response', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('payment', sa.Column('gateway_order_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('payment', sa.Column('gateway_signature', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('payment', sa.Column('currency', sa.VARCHAR(length=3), server_default=sa.text("'INR'::character varying"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_index(op.f('ix_payment_txn_id'), table_name='payment')
    op.create_index(op.f('ix_payment_txn_id'), 'payment', ['txn_id'], unique=False)
    op.create_unique_constraint(op.f('uq_payment_txn_id'), 'payment', ['txn_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_payment_order_method'), 'payment', ['order_id', 'method'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_payment_user_id'), 'payment', ['user_id'], unique=False)
    op.alter_column('payment', 'txn_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('order', sa.Column('payment_method', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.add_column('ebookpurchase', sa.Column('last_renewed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('ebookpurchase', sa.Column('renewal_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_ebookpurchase_gateway_order_id'), table_name='ebookpurchase')
    op.create_foreign_key(op.f('book_category_id_fkey'), 'book', 'category', ['category_id'], ['id'])
    op.drop_index(op.f('ix_book_is_deleted'), table_name='book')
    op.alter_column('book', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('order_event',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(), server_default=sa.text("'system'::character varying"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name=op.f('order_event_order_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('order_event_pkey'))
    )
    op.create_index(op.f('ix_order_event_order_id'), 'order_event', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_event_event_type'), 'order_event', ['event_type'], unique=False)
    op.create_table('cancellationrequest',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('cancellationrequest_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('additional_notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('refund_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('refund_method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('refund_reference', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('admin_notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('requested_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('processed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name=op.f('fk_cancellation_order')),
    sa.ForeignKeyConstraint(['processed_by'], ['user.id'], name=op.f('fk_cancellation_processed_by')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_cancellation_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('cancellationrequest_pkey'))
    )
    op.create_table('email_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('to_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('error', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('email_log_pkey'))
    )
    op.create_table('book_image',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name=op.f('book_image_book_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('book_image_pkey'))
    )
    op.create_index(op.f('ix_book_image_book_id'), 'book_image', ['book_id'], unique=False)
    op.drop_table('emaillog')
    # ### end Alembic commands ###
