"""make user_id nullable for guest orders

Revision ID: fa1dac94d28d
Revises: 2e713e304f9e
Create Date: 2026-01-13 15:59:05.312006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'fa1dac94d28d'
down_revision: Union[str, Sequence[str], None] = '2e713e304f9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('order', sa.Column('guest_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('order', sa.Column('guest_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('order', sa.Column('guest_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('order', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order', 'address_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('order', sa.Column('payment_method', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('order', 'address_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('order', 'guest_phone')
    op.drop_column('order', 'guest_name')
    op.drop_column('order', 'guest_email')
    
  
    
    # ### end Alembic commands ###
